// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/jasa.proto

package jasapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JasaService_GetServiceDetail_FullMethodName = "/jasa.JasaService/GetServiceDetail"
)

// JasaServiceClient is the client API for JasaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JasaServiceClient interface {
	GetServiceDetail(ctx context.Context, in *GetServiceDetailRequest, opts ...grpc.CallOption) (*GetServiceDetailResponse, error)
}

type jasaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJasaServiceClient(cc grpc.ClientConnInterface) JasaServiceClient {
	return &jasaServiceClient{cc}
}

func (c *jasaServiceClient) GetServiceDetail(ctx context.Context, in *GetServiceDetailRequest, opts ...grpc.CallOption) (*GetServiceDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceDetailResponse)
	err := c.cc.Invoke(ctx, JasaService_GetServiceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JasaServiceServer is the server API for JasaService service.
// All implementations must embed UnimplementedJasaServiceServer
// for forward compatibility.
type JasaServiceServer interface {
	GetServiceDetail(context.Context, *GetServiceDetailRequest) (*GetServiceDetailResponse, error)
	mustEmbedUnimplementedJasaServiceServer()
}

// UnimplementedJasaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJasaServiceServer struct{}

func (UnimplementedJasaServiceServer) GetServiceDetail(context.Context, *GetServiceDetailRequest) (*GetServiceDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceDetail not implemented")
}
func (UnimplementedJasaServiceServer) mustEmbedUnimplementedJasaServiceServer() {}
func (UnimplementedJasaServiceServer) testEmbeddedByValue()                     {}

// UnsafeJasaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JasaServiceServer will
// result in compilation errors.
type UnsafeJasaServiceServer interface {
	mustEmbedUnimplementedJasaServiceServer()
}

func RegisterJasaServiceServer(s grpc.ServiceRegistrar, srv JasaServiceServer) {
	// If the following call panics, it indicates UnimplementedJasaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JasaService_ServiceDesc, srv)
}

func _JasaService_GetServiceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasaServiceServer).GetServiceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JasaService_GetServiceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasaServiceServer).GetServiceDetail(ctx, req.(*GetServiceDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JasaService_ServiceDesc is the grpc.ServiceDesc for JasaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JasaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jasa.JasaService",
	HandlerType: (*JasaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceDetail",
			Handler:    _JasaService_GetServiceDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jasa.proto",
}
