// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/jasa.proto

package jasapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceDetailRequest) Reset() {
	*x = GetServiceDetailRequest{}
	mi := &file_proto_jasa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDetailRequest) ProtoMessage() {}

func (x *GetServiceDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jasa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDetailRequest.ProtoReflect.Descriptor instead.
func (*GetServiceDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_jasa_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceDetailRequest) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type GetServiceDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BasePrice      int64                  `protobuf:"varint,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Spesifications []*Spesification       `protobuf:"bytes,4,rep,name=spesifications,proto3" json:"spesifications,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceDetailResponse) Reset() {
	*x = GetServiceDetailResponse{}
	mi := &file_proto_jasa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDetailResponse) ProtoMessage() {}

func (x *GetServiceDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jasa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDetailResponse.ProtoReflect.Descriptor instead.
func (*GetServiceDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_jasa_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetServiceDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceDetailResponse) GetBasePrice() int64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *GetServiceDetailResponse) GetSpesifications() []*Spesification {
	if x != nil {
		return x.Spesifications
	}
	return nil
}

type Spesification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InputType     string                 `protobuf:"bytes,3,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	IsRequired    bool                   `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	Values        []*SpesificationValue  `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spesification) Reset() {
	*x = Spesification{}
	mi := &file_proto_jasa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spesification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spesification) ProtoMessage() {}

func (x *Spesification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jasa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spesification.ProtoReflect.Descriptor instead.
func (*Spesification) Descriptor() ([]byte, []int) {
	return file_proto_jasa_proto_rawDescGZIP(), []int{2}
}

func (x *Spesification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spesification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spesification) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *Spesification) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *Spesification) GetValues() []*SpesificationValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type SpesificationValue struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value           string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AdditionalPrice int64                  `protobuf:"varint,3,opt,name=additional_price,json=additionalPrice,proto3" json:"additional_price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpesificationValue) Reset() {
	*x = SpesificationValue{}
	mi := &file_proto_jasa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpesificationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpesificationValue) ProtoMessage() {}

func (x *SpesificationValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jasa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpesificationValue.ProtoReflect.Descriptor instead.
func (*SpesificationValue) Descriptor() ([]byte, []int) {
	return file_proto_jasa_proto_rawDescGZIP(), []int{3}
}

func (x *SpesificationValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpesificationValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SpesificationValue) GetAdditionalPrice() int64 {
	if x != nil {
		return x.AdditionalPrice
	}
	return 0
}

var File_proto_jasa_proto protoreflect.FileDescriptor

const file_proto_jasa_proto_rawDesc = "" +
	"\n" +
	"\x10proto/jasa.proto\x12\x04jasa\"8\n" +
	"\x17GetServiceDetailRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\"\x9a\x01\n" +
	"\x18GetServiceDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_price\x18\x03 \x01(\x03R\tbasePrice\x12;\n" +
	"\x0espesifications\x18\x04 \x03(\v2\x13.jasa.SpesificationR\x0espesifications\"\xa5\x01\n" +
	"\rSpesification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_type\x18\x03 \x01(\tR\tinputType\x12\x1f\n" +
	"\vis_required\x18\x04 \x01(\bR\n" +
	"isRequired\x120\n" +
	"\x06values\x18\x05 \x03(\v2\x18.jasa.SpesificationValueR\x06values\"e\n" +
	"\x12SpesificationValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12)\n" +
	"\x10additional_price\x18\x03 \x01(\x03R\x0fadditionalPrice2`\n" +
	"\vJasaService\x12Q\n" +
	"\x10GetServiceDetail\x12\x1d.jasa.GetServiceDetailRequest\x1a\x1e.jasa.GetServiceDetailResponseB\x15Z\x13proto/jasapb;jasapbb\x06proto3"

var (
	file_proto_jasa_proto_rawDescOnce sync.Once
	file_proto_jasa_proto_rawDescData []byte
)

func file_proto_jasa_proto_rawDescGZIP() []byte {
	file_proto_jasa_proto_rawDescOnce.Do(func() {
		file_proto_jasa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jasa_proto_rawDesc), len(file_proto_jasa_proto_rawDesc)))
	})
	return file_proto_jasa_proto_rawDescData
}

var file_proto_jasa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_jasa_proto_goTypes = []any{
	(*GetServiceDetailRequest)(nil),  // 0: jasa.GetServiceDetailRequest
	(*GetServiceDetailResponse)(nil), // 1: jasa.GetServiceDetailResponse
	(*Spesification)(nil),            // 2: jasa.Spesification
	(*SpesificationValue)(nil),       // 3: jasa.SpesificationValue
}
var file_proto_jasa_proto_depIdxs = []int32{
	2, // 0: jasa.GetServiceDetailResponse.spesifications:type_name -> jasa.Spesification
	3, // 1: jasa.Spesification.values:type_name -> jasa.SpesificationValue
	0, // 2: jasa.JasaService.GetServiceDetail:input_type -> jasa.GetServiceDetailRequest
	1, // 3: jasa.JasaService.GetServiceDetail:output_type -> jasa.GetServiceDetailResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_jasa_proto_init() }
func file_proto_jasa_proto_init() {
	if File_proto_jasa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jasa_proto_rawDesc), len(file_proto_jasa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jasa_proto_goTypes,
		DependencyIndexes: file_proto_jasa_proto_depIdxs,
		MessageInfos:      file_proto_jasa_proto_msgTypes,
	}.Build()
	File_proto_jasa_proto = out.File
	file_proto_jasa_proto_goTypes = nil
	file_proto_jasa_proto_depIdxs = nil
}
